---
# Swap and memory management configuration for tiny VMs

- name: Get system memory information
  setup:
    filter: ansible_memtotal_mb
  tags: ['swap']

- name: Set swap configuration facts
  set_fact:
    use_zram: "{{ ansible_memtotal_mb < performance_optimization_zram_threshold_mb }}"
    swap_size_mb: "{{ (ansible_memtotal_mb * performance_optimization_swap_size_ratio) | int }}"
  tags: ['swap']

- name: Display swap strategy
  debug:
    msg: "Using {{ 'ZRAM' if use_zram else 'swapfile' }} swap strategy for {{ ansible_memtotal_mb }}MB RAM system"
  tags: ['swap']

# ZRAM Configuration (Ubuntu version gated)
- name: Ensure correct ZRAM implementation is used (remove conflicting packages)
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    update_cache: yes
  loop:
    # On 22.04/24.04 prefer systemd-zram-generator and ensure zram-tools is absent
    - { name: 'systemd-zram-generator', state: "{{ 'present' if (ansible_distribution_major_version | int) >= 22 else 'absent' }}" }
    - { name: 'zram-tools', state: "{{ 'present' if (ansible_distribution_major_version | int) < 22 else 'absent' }}" }
  when: use_zram
  tags: ['swap']

- name: Check if ZRAM kernel module is available
  stat:
    path: /lib/modules/{{ ansible_kernel }}/kernel/drivers/block/zram/zram.ko
  register: zram_module_check
  when: use_zram and (ansible_distribution_major_version | int) >= 22
  tags: ['swap']

- name: Ensure ZRAM kernel module is loaded
  modprobe:
    name: zram
    state: present
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']

- name: Display ZRAM module status
  debug:
    msg: "ZRAM kernel module {{ 'available and loaded' if zram_module_check.stat.exists else 'not available in kernel' }}"
  when: use_zram and (ansible_distribution_major_version | int) >= 22
  tags: ['swap']

- name: Set fallback to swapfile if ZRAM not available
  set_fact:
    use_swapfile_fallback: "{{ use_zram and (ansible_distribution_major_version | int) >= 22 and not zram_module_check.stat.exists }}"
  when: use_zram and (ansible_distribution_major_version | int) >= 22
  tags: ['swap']

- name: Display fallback strategy
  debug:
    msg: "ZRAM not available, using swapfile fallback for {{ swap_size_mb }}MB"
  when: use_swapfile_fallback | default(false)
  tags: ['swap']

- name: Configure systemd-zram-generator (Ubuntu >= 22.04)
  copy:
    dest: /etc/systemd/zram-generator.conf
    mode: '0644'
    content: |
      [zram0]
      zram-size = {{ swap_size_mb }}M
      compression-algorithm = {{ performance_optimization_zram_algo }}
      swap-priority = 100
      # Additional options for better stability
      max-zram-size = {{ swap_size_mb }}M
      # Ensure we don't exceed available memory
      memory-limit = {{ (ansible_memtotal_mb * 0.8) | int }}M
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  notify: systemd daemon-reload
  tags: ['swap']

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']

- name: Wait for ZRAM device to be available
  wait_for:
    path: /dev/zram0
    timeout: 30
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']

- name: Check ZRAM device status
  shell: cat /sys/block/zram0/comp_algorithm
  register: zram_algo_check
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  failed_when: false
  tags: ['swap']

- name: Display ZRAM device information
  debug:
    msg: "ZRAM device algorithms: {{ zram_algo_check.stdout }}"
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_algo_check.stdout is defined
  tags: ['swap']

- name: Enable swap on zram (Ubuntu >= 22.04)
  systemd:
    name: systemd-zram-setup@zram0.service
    enabled: yes
    state: started
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']
  register: zram_service_result
  failed_when: false

- name: Check ZRAM service status
  systemd:
    name: systemd-zram-setup@zram0.service
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']
  register: zram_status

- name: Display ZRAM status
  debug:
    msg: "ZRAM service status: {{ zram_status.status.ActiveState }}"
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists
  tags: ['swap']

- name: Fallback to swapfile if ZRAM fails
  debug:
    msg: "ZRAM failed to start, falling back to swapfile configuration"
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_status.status.ActiveState != "active"
  tags: ['swap']

- name: Create fallback swapfile if ZRAM fails
  command: fallocate -l {{ swap_size_mb }}M /swapfile
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_status.status.ActiveState != "active" and not ansible_check_mode
  tags: ['swap']

- name: Set fallback swapfile permissions
  file:
    path: /swapfile
    mode: '0600'
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_status.status.ActiveState != "active"
  tags: ['swap']

- name: Format fallback swapfile
  command: mkswap /swapfile
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_status.status.ActiveState != "active" and not ansible_check_mode
  tags: ['swap']

- name: Enable fallback swapfile
  command: swapon /swapfile
  when: use_zram and (ansible_distribution_major_version | int) >= 22 and zram_module_check.stat.exists and zram_status.status.ActiveState != "active" and not ansible_check_mode
  tags: ['swap']

# Direct fallback when ZRAM module not available
- name: Check if swapfile already exists
  stat:
    path: /swapfile
  register: swapfile_check_fallback
  when: use_swapfile_fallback | default(false)
  tags: ['swap']

- name: Create swapfile when ZRAM not available
  command: fallocate -l {{ swap_size_mb }}M /swapfile
  when: use_swapfile_fallback | default(false) and not swapfile_check_fallback.stat.exists and not ansible_check_mode
  tags: ['swap']

- name: Set swapfile permissions when ZRAM not available
  file:
    path: /swapfile
    mode: '0600'
  when: use_swapfile_fallback | default(false) and not swapfile_check_fallback.stat.exists
  tags: ['swap']

- name: Format swapfile when ZRAM not available
  command: mkswap /swapfile
  when: use_swapfile_fallback | default(false) and not swapfile_check_fallback.stat.exists and not ansible_check_mode
  tags: ['swap']

- name: Enable swapfile when ZRAM not available
  command: swapon /swapfile
  when: use_swapfile_fallback | default(false) and not swapfile_check_fallback.stat.exists and not ansible_check_mode
  tags: ['swap']

- name: Configure zram-tools (Ubuntu 20.04)
  template:
    src: zramswap.j2
    dest: /etc/default/zramswap
    backup: yes
  when: use_zram and (ansible_distribution_major_version | int) < 22
  notify: restart zramswap
  tags: ['swap']

- name: Enable and start zramswap service (Ubuntu 20.04)
  systemd:
    name: zramswap
    enabled: yes
    state: started
  when: use_zram and (ansible_distribution_major_version | int) < 22
  tags: ['swap']

# Swapfile Configuration (fallback for larger VMs)
- name: Check if swapfile already exists
  stat:
    path: /swapfile
  register: swapfile_check
  when: not use_zram
  tags: ['swap']

- name: Create swapfile
  command: fallocate -l {{ swap_size_mb }}M /swapfile
  when: not use_zram and not swapfile_check.stat.exists
  tags: ['swap']

- name: Set swapfile permissions
  file:
    path: /swapfile
    mode: '0600'
  when: not use_zram
  tags: ['swap']

- name: Format swapfile
  command: mkswap /swapfile
  when: not use_zram and not swapfile_check.stat.exists
  tags: ['swap']

- name: Enable swapfile
  command: swapon /swapfile
  when: not use_zram and not swapfile_check.stat.exists
  tags: ['swap']

- name: Add swapfile to fstab
  lineinfile:
    path: /etc/fstab
    line: '/swapfile none swap sw 0 0'
    state: present
  when: not use_zram
  tags: ['swap']

# Memory management sysctl settings (applied regardless of swap type)
- name: Configure memory management sysctl settings
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    sysctl_file: /etc/sysctl.d/60-memory-optimization.conf
    reload: yes
  loop:
    # Conservative swappiness for tiny VMs (reduce swap usage)
    - { name: 'vm.swappiness', value: '{{ performance_optimization_swappiness }}' }
    # Reduce cache pressure to keep more cache in memory
    - { name: 'vm.vfs_cache_pressure', value: '{{ performance_optimization_vfs_cache_pressure }}' }
    # Dirty memory settings for better I/O performance
    - { name: 'vm.dirty_background_ratio', value: '5' }
    - { name: 'vm.dirty_ratio', value: '10' }
    # Reduce dirty writeback time for better responsiveness
    - { name: 'vm.dirty_writeback_centisecs', value: '500' }
    - { name: 'vm.dirty_expire_centisecs', value: '3000' }
    # Memory overcommit settings
    - { name: 'vm.overcommit_memory', value: '1' }
    - { name: 'vm.overcommit_ratio', value: '50' }
  tags: ['swap', 'sysctl']
